# Etapa de construção
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia o arquivo .csproj diretamente, pois está no mesmo diretório
COPY ["GerenciadorDeTarefas.csproj", "./"]
RUN dotnet restore "GerenciadorDeTarefas.csproj"

# Copia todos os arquivos para o contexto de build
COPY . . 
WORKDIR "/src"
RUN dotnet build "GerenciadorDeTarefas.csproj" -c Release -o /app/build

# Etapa de publicação
FROM build AS publish
RUN dotnet publish "GerenciadorDeTarefas.csproj" -c Release -o /app/publish

# Etapa final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "GerenciadorDeTarefas.dll"]
