services:
  gerenciador-de-tarefas:
    image: gerenciador-de-tarefas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7245:7245"  # HTTPS
      - "5269:5269"  # HTTP
    volumes:
      - ./dataProtectionKeys:/root/.aspnet/DataProtection-Keys  # Persistência das chaves de proteção de dados
      - ./Data/certificado.pfx:/https/certificado.pfx  # Certificado
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://*:7245;http://*:5269
