version: '3.8'

services:
  gerenciador-de-tarefas:
    image: gerenciador-de-tarefas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "17435:8080"  # HTTP
      - "5269:443"    # HTTPS (para o Kestrel no Docker)
