# Etapa de construção
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GerenciadorDeTarefas/GerenciadorDeTarefas.csproj", "GerenciadorDeTarefas/"]
RUN dotnet restore "GerenciadorDeTarefas/GerenciadorDeTarefas.csproj"
COPY . .
WORKDIR "/src/GerenciadorDeTarefas"
RUN dotnet build "GerenciadorDeTarefas.csproj" -c Release -o /app/build

# Etapa de publicação
FROM build AS publish
RUN dotnet publish "GerenciadorDeTarefas.csproj" -c Release -o /app/publish

# Etapa final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GerenciadorDeTarefas.dll"]
